services:
  - type: web
    name: ourfinancetracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ourfinancetracker_site.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oft-db
          property: connectionString
      - key: SECRET_KEY
        sync: false          # defines no YAML; preenches no Dashboard
      - key: ALLOWED_HOSTS
        value: ourfinancetracker.onrender.com,ourfinancetracker.com

databases:
  - name: oft-db
    plan: free
