services:
  - type: web
    name: ourfinancetracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ourfinancetracker_site.wsgi"
    envVars:
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_PORT
        value: 6543
      - key: SECRET_KEY
        value: ${SECRET_KEY}
