# Generated by Django 5.2.1 on 2025-06-03 13:55

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(default=core.models.get_default_account_type, on_delete=django.db.models.deletion.PROTECT, to='core.accounttype'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, default=core.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense'), ('IV', 'Investment')], max_length=2),
        ),
    ]
