# Generated by Django 5.2.1 on 2025-06-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dateperiod",
            options={"ordering": ["-year", "-month"]},
        ),
        migrations.RemoveConstraint(
            model_name="dateperiod",
            name="unique_dateperiod_year_month",
        ),
        migrations.AlterUniqueTogether(
            name="dateperiod",
            unique_together={("year", "month")},
        ),
    ]
