# Generated by Django 5.2.1 on 2025-06-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="transactions", to="core.tag"
            ),
        ),
    ]
