# Generated by Django 5.2.1 on 2025-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_account_account_type_alter_account_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
