# Generated by Django 5.2.1 on 2025-06-15 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_account_account_type_alter_account_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="account",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="accountbalance",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="dateperiod",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="transactiontag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_account_user_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountbalance",
            constraint=models.UniqueConstraint(
                fields=("account", "period"),
                name="unique_accountbalance_account_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_category_user_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="dateperiod",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="unique_dateperiod_year_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("from_currency", "to_currency", "rate_date"),
                name="unique_exchangerate_from_to_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_tag_user_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontag",
            constraint=models.UniqueConstraint(
                fields=("transaction", "tag"), name="unique_transactiontag_tx_tag"
            ),
        ),
    ]
