# Generated by Django 5.2.1 on 2025-06-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_dateperiod_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dateperiod",
            unique_together=set(),
        ),
    ]
