# Generated by Django 5.2.1 on 2025-06-16 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_dateperiod_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dateperiod",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2045),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="dateperiod",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="unique_year_month"
            ),
        ),
    ]
