# Generated by Django 5.2.1 on 2025-06-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tag_user_alter_tag_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="position",
        ),
    ]
