# Generated by Django 5.2.1 on 2025-06-15 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_account_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dateperiod",
            name="month",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
    ]
