# Generated by Django 5.2.1 on 2025-06-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_tag_options_remove_tag_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("position", "name"), "verbose_name_plural": "tags"},
        ),
        migrations.AddField(
            model_name="tag",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
