
# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dateperiod_year_dateperiod_unique_year_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_cleared',
        ),
    ]
