# Generated by Django 5.1.4 on 2025-06-26 22:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_is_cleared"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="editable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_system",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("EX", "Expense"),
                    ("IN", "Income"),
                    ("IV", "Investment"),
                    ("TR", "Transfer"),
                    ("AJ", "System adjustment"),
                ],
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="MonthlySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=7, unique=True)),
                (
                    "investimentos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "despesas",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "receitas_nao_lanc",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "despesas_ajustadas",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_dirty", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["period"],
                "indexes": [
                    models.Index(
                        fields=["is_dirty"], name="core_monthl_is_dirt_47448a_idx"
                    )
                ],
            },
        ),
    ]
