# Generated by Django 5.2.1 on 2025-06-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accountbalance",
            name="idx_accountbalance_account_period",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="idx_transaction_user_date",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="idx_transaction_period_type",
        ),
    ]
