# Generated by Django 5.2.1 on 2025-06-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_performance_indexes"),
    ]

    operations = []
