# Generated by Django 5.1.4 on 2025-06-29 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dateperiod",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="editable",
            field=models.BooleanField(
                default=True, help_text="Se False, transação é só de leitura"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_estimated",
            field=models.BooleanField(
                default=False, help_text="Transação estimada/calculada automaticamente"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_system",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Transação automática do sistema (não afeta saldos das contas)",
            ),
        ),
    ]
