# Generated by Django 5.1.4 on 2025-07-27 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_adjustment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "name"], name="core_accoun_user_id_393a41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "account_type"], name="core_accoun_user_id_5d8777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "created_at"], name="core_accoun_user_id_b9c217_idx"
            ),
        ),
    ]
