# Generated by Django 5.1.4 on 2025-08-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_account_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ("position", "name")},
        ),
        migrations.AddIndex(
            model_name="accountbalance",
            index=models.Index(
                fields=["account", "period"], name="core_accoun_account_3be262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountbalance",
            index=models.Index(
                fields=["period"], name="core_accoun_period__63b5e7_idx"
            ),
        ),
    ]
