# Generated by Django 5.1.4 on 2025-08-11 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_account_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="(Optional) Category associated with this tag",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="editable",
            field=models.BooleanField(
                default=True, help_text="If False, transaction is read-only"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_estimated",
            field=models.BooleanField(
                default=False,
                help_text="Estimated/automatically calculated transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_system",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="System automatic transaction (does not affect account balances)",
            ),
        ),
    ]
