# Generated by Django 5.1.4 on 2025-08-15 22:20

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_tag_category_alter_transaction_editable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="base_currency",
            field=models.ForeignKey(
                blank=True,
                default=core.models.get_default_currency_id,
                help_text="Base currency for reporting",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_base_currency",
                to="core.currency",
            ),
        ),
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fx_base_rates",
                        to="core.currency",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fx_quote_rates",
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "base__code", "quote__code"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "base", "quote"), name="unique_fx_rate"
                    )
                ],
            },
        ),
    ]
