# Generated by Django 5.1.11 on 2025-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_recurring_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="kpi_goals",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
