# Generated by Django 5.1.11 on 2025-08-16 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_usersettings_kpi_goals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_estimated", True)),
                fields=("user", "period", "type", "category", "account"),
                name="unique_estimate_per_scope",
            ),
        ),
    ]
