# Generated by Django 5.1.11 on 2025-08-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_transaction_unique_estimate_per_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="investment_flow",
            field=models.CharField(
                blank=True,
                choices=[("IN", "Reinforcement"), ("OUT", "Withdrawal")],
                help_text="Direction of investment cash flow",
                max_length=3,
                null=True,
            ),
        ),
    ]
