# Generated by Django 5.1.11 on 2025-08-17 18:02

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_transaction_unique_estimate_per_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="unique_account_user_name",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("user"),
                name="unique_account_user_name_ci",
            ),
        ),
    ]
