# Generated by Django 5.1.11 on 2025-08-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_account_unique_account_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="blocked",
            field=models.BooleanField(
                default=False,
                help_text="If true, category is reserved and hidden from normal use",
            ),
        ),
    ]
