# Generated by Codex on 2026-04-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_category_blocked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monthlysummary",
            old_name="investimentos",
            new_name="investments",
        ),
        migrations.RenameField(
            model_name="monthlysummary",
            old_name="despesas",
            new_name="estimated_expenses",
        ),
        migrations.RenameField(
            model_name="monthlysummary",
            old_name="receitas_nao_lanc",
            new_name="unposted_income",
        ),
        migrations.RenameField(
            model_name="monthlysummary",
            old_name="despesas_ajustadas",
            new_name="adjusted_expenses",
        ),
    ]
